module.exports = {
	QUOTES_EN: [
		['Alex Lowe', 'The best climber in the world is the one who\'s having the most fun.'],
		['A dying Star Trek character', 'Many years ago, I climbed the mountains, even thought it is forbidden. Things are not as they teach us; the world is hollow, and I have touched the sky.'],
		['Barry Blanchard', 'It doesn\'t have to be fun to be fun.'],
		['Ben Moon', 'Variety is the spice of life. Variety will give you good skills, stop you stagnating and keep you motivated.'],
		['Chuck Pratt', 'I don\'t want to write about climbing; I don\'t want to talk about it; I don\'t want to photograph it; I don\'t want to think about it; all I want to do is do it.'],
		['Dave Graham', 'I remember all the moves of every problem I\'ve ever done. This is what keeps me up at night.'],
		['Ed Viesturs', 'It\'s a round trip. Getting to the summit is optional, getting down is mandatory.'],
		['Edmund Hillary', 'It is not the mountain we conquer, but ourselves.'],
		['Edmund Hillary', 'Nobody climbs mountains for scientific reasons. Science is used to raise money for the expeditions, but you really climb for the hell of it.'],
		['Edward Abbey', 'In the American Southwest, I began a lifelong love affair with a pile of rock.'],
		['Evan Hardin', 'Good judgment comes from experience. Experience comes from bad judgment.'],
		['Geoff Jennings', 'I climb much harder in my posts than I do in real life.'],
		['George Mallory, when asked \'Why do you want to climb Mt. Everest?', 'Because it is there.'],
		['George Mallory', 'We do not live to eat and make money, we eat and make money to be able to enjoy life.'],
		['Greg Child', 'Somewhere between the bottom of the climb and the summit is the answer to the mystery why we climb.'],
		['Guillaume Dargaud', 'The difference between climbers and normal workers is that climbers are glad of the Mondays, so they can rest.'],
		['Hermann Buhl', 'Mountains have a way of dealing with overconfidence.'],
		['John Black', 'The hardest thing about Fontainebleau is spelling it.'],
		['John Muir', 'Doubly happy, however, is the man to whom lofty mountain tops are within reach.'],
		['Jack Kerouac', 'In the end, you won’t remember the time you spent working in the office or mowing your lawn. Climb that goddamn mountain.'],
		['Jim Wickwire', 'I\'ve climbed with some of the best climbers in the world, more importantly, to me, they are some of the best people in the world. That\'s another reason why I climb.'],
		['Margaret Young', 'Climbing is as close as we can come to flying.'],
		['Mark Twain', 'There is probably no pleasure equal to the pleasure of climbing a dangerous Alp; but it is a pleasure which is confined strictly to people who can find pleasure in it.'],
		['Randy Leavitt', 'I\'ve tried many sports, but climbing is the best. The beauty of this sport is that no matter how good you get, you can always find a way to challenge yourself.'],
		['Reinhold Messner', 'Bolts are the murder of the impossible.'],
		['Reinhold Messner', 'Mountains are not fair or unfair, they are just dangerous.'],
		['Roman Coval', 'In Ukraine, we have enough climbers without fingers and toes — the only problem is to change bootsize.'],
		['Tom Patey', 'Good climbing and good company often go together: each is essential to the enjoyment of the other.'],
		['Unknown Author', 'Mountain climbing is extended periods of intense boredom, interrupted by occasional moments of sheer terror.'],
		['Unknown Author', 'The three rules of mountaineering:\nIt’s always further than it looks.\nIt’s always taller than it looks.\nAnd it’s always harder than it looks.'],
		['Unknown Author', 'There are old climbers, there are bold climbers, but there are no old bold climbers!'],
		['Warren Harding', 'As I hammered in the last bolt and staggered over the rim, it was not at all clear to me who was the conqueror and who was the conquered. I do recall that El Cap seemed to be in much better condition than I was.'],
		['Wolfgang Güllich', 'A man doesn\'t go to drink coffee after climbing, coffee is integral part of the climbing.'],
		['Wolfgang Güllich', 'Climbing does not mean just competition and performance. It has other qualities that are important: going on trips, meeting people, seeing other cultures...'],
		['Wolfgang Güllich', 'If climbing is an art, then creativity is its main component.'],
		['Will Niccolls', 'Remember that time spent on a rock climb isn’t subtracted from your life span.']
	]
}
;
